name: conda recipe

# Controls when the workflow will run
on: 
  # Triggers the workflow on schedule but only for the default branch (which is master)
  schedule:
   - cron: '0 7 5,20 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_recipe:
    name: test bioconda recipes on ${{ matrix.os }} with python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest','macos-13']
        python-version: ['3.8']
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda
          activate-environment: test

      - name: Install binette with mamba
        shell: bash -l {0}
        run: |
            mamba install -y binette

      - name: Get binette version
        id: binette_version
        shell: bash -l {0}
        run: |
            BINETTE_VERSION=$(binette --version | awk '{print $NF}')  # Extract the version number
            echo "Binette version: $BINETTE_VERSION"
            echo "BINETTE_VERSION=$BINETTE_VERSION" >> $GITHUB_ENV  # Export for later steps

      - name: Checkout the corresponding Binette version
        uses: actions/checkout@v4
        with:
          ref: "v${{ env.BINETTE_VERSION }}"
          # path: "binette_source"

      - name: Run tests with pytest
        shell: bash -l {0}
        run: |
          cd binette_source
          pip install pytest
          pytest